#config/packages/nelmio_cors.yaml
nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['*']
        allow_headers: ['Content-Type', 'Authorization','Origin', 'Accept']
        allow_methods: ['POST', 'PUT', 'GET','OPTIONS']
        expose_headers: ['Location']
        max_age: 3600
        hosts: ['http://127.0.0.1:8001']
        origin_regex: true
        forced_allow_origin_value: ~
    paths:
        '^/':
            allow_credentials: true
            allow_origin: ['*']
            allow_headers: ['Content-Type', 'Authorization','Origin', 'Accept']
            allow_methods: ['POST', 'PUT', 'GET','OPTIONS']
            hosts: ['http://127.0.0.1:8001']
            origin_regex: true
            max_age: 3600
